# Generated by Django 3.0.5 on 2020-05-17 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '__first__'),
        ('student', '0002_auto_20200517_1217'),
        ('teacher', '0002_auto_20200517_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name')),
                ('_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='Code')),
                ('_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_homework', to='homework.MainModel', verbose_name='Домашнее задание')),
                ('_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_student', to='student.User', verbose_name='Ученик')),
                ('_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_teacher', to='teacher.User', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневник',
                'db_table': 'diary',
            },
        ),
    ]
