# Generated by Django 3.0.5 on 2020-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
