# Generated by Django 3.0.5 on 2020-06-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_mainmodel_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='mainmodel',
            old_name='_name',
            new_name='name',
        ),
    ]
