# Generated by Django 3.0.5 on 2020-04-28 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sclass', '0002_auto_20200428_0922'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'default_permissions': ('add', 'change', 'delete'), 'default_related_name': 'user_student', 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученик'},
        ),
        migrations.AddField(
            model_name='student',
            name='_sclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_student', to='sclass.MainModel', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
