# Generated by Django 3.0.5 on 2020-05-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200503_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenstudent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
