# Generated by Django 3.0.5 on 2020-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_mainmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='height',
            field=models.IntegerField(db_column='video_height', default=315, verbose_name='width'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='video_src',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='video url'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='width',
            field=models.IntegerField(db_column='video_width', default=560, verbose_name='width'),
        ),
    ]
