# Generated by Django 2.2.3 on 2020-04-27 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 16, 37, 15, 897310)),
        ),
    ]
