# Generated by Django 3.0.5 on 2020-05-02 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200427_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 21, 11, 6, 474183)),
        ),
    ]
