# Generated by Django 3.0.3 on 2020-02-05 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200205_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 19, 17, 50, 229197)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ветер'),
        ),
    ]
