# Generated by Django 3.0.5 on 2020-05-03 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200503_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 17, 33, 55, 803628)),
        ),
    ]
