FROM python:3.7 
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /code/opt/backend/django/www
RUN mkdir -p /code/opt/backend/bot
RUN mkdir -p /code/statics
RUN mkdir -p /code/media

RUN pip install --upgrade pip
RUN pip3 install django \
	scrapy \
	scrapy-djangoitem \
	django-filter \
	django-select2 \
	django-select2-forms \
	Pillow \
	django-easy-select2 \
	requests \
	gunicorn \
	django-redis \
	djangorestframework \
	markdown \
	django-filter\
	psycopg2-binary \
	celery  \
	django-celery-results \
	django_celery_beat \
	pytelegrambotapi \
    django-rest-passwordreset \
    django-rest-swagger \
    django-allauth \
    django-rest-auth \
    django-password-reset