# Generated by Django 2.2.6 on 2020-02-05 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 17, 49, 1, 318676)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ветер'),
        ),
    ]
