# Generated by Django 3.0.5 on 2020-05-05 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(blank=True, max_length=4, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Буква класса',
                'verbose_name_plural': 'Буквы класса',
                'db_table': 'class_letter',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_datecreate', models.DateField(blank=True, default=datetime.datetime(2020, 5, 5, 14, 33, 42, 621509), null=True, verbose_name='Год создания 1-го класса')),
                ('_active', models.BooleanField(default=True)),
                ('_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sclass_letter', to='sclass.ClassLetter', verbose_name='Буква класса')),
                ('_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sclass_school', to='school.MainModel', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класс',
                'db_table': 'sclass',
            },
        ),
    ]
