# Generated by Django 3.0.5 on 2020-04-28 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='_datecreate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 28, 9, 22, 35, 26664), null=True, verbose_name='Год создания 1-го класса'),
        ),
    ]
