# Generated by Django 3.0.5 on 2020-05-05 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parentuser', '0002_auto_20200505_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenparent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='ParentUser'),
        ),
    ]
