# Generated by Django 3.0.5 on 2020-04-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sclass', '0001_initial'),
        ('lesson', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='_sclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sclass.MainModel', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.MainModel', verbose_name='Предмет'),
        ),
    ]
