from .settings import *

SITE_ID = 2
AUTH_USER_MODEL = 'teacher.Teacher'

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'

ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True

SITE_NAME = "school"
SITE_DOMAIN = "teacher.school.local"
BASE_URL = 'https://teacher.school.local'

FILE_UPLOAD_MAX_MEMORY_SIZE=52428800