# Generated by Django 3.0.5 on 2020-04-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_auto_20200423_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentstudentmm',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_mm_student', to='parent.Parent', verbose_name='parent_mm_student'),
        ),
    ]
