# Generated by Django 3.0.5 on 2020-04-28 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_auto_20200423_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'default_permissions': ('add', 'change', 'delete'), 'default_related_name': 'user_parent', 'verbose_name': 'Родитель', 'verbose_name_plural': 'Родитель'},
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
